/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jfilechooserdemo.resources;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author Gabriel Fernandes
 */
public class JFileChooserDemo extends javax.swing.JFrame {

    private Object textarea;

    /**
     * Creates new form JFileChooserDemo
     */
    public JFileChooserDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        textFieldNomeRota = new javax.swing.JTextField();
        labelNomeRota = new javax.swing.JLabel();
        labelTempoRota = new javax.swing.JLabel();
        textFieldTempoRota = new javax.swing.JTextField();
        labelInstitutional = new javax.swing.JLabel();
        textFieldInstitutional = new javax.swing.JTextField();
        textFieldSecurity = new javax.swing.JTextField();
        labelSecurity = new javax.swing.JLabel();
        btSearchSecurity = new javax.swing.JButton();
        btSearchInstitutional = new javax.swing.JButton();
        labelFilmes = new javax.swing.JLabel();
        textFieldMovies = new javax.swing.JTextField();
        btSearchMovies = new javax.swing.JButton();
        labelAdvertising = new javax.swing.JLabel();
        textFieldadvertising = new javax.swing.JTextField();
        btSearchAvertising = new javax.swing.JButton();
        labelIconIrizar = new javax.swing.JLabel();
        btGenerateRoute = new javax.swing.JButton();
        btEditRoute = new javax.swing.JButton();
        btAddInstitutional = new javax.swing.JButton();
        btAddSecurityMovie = new javax.swing.JButton();
        btAddMovie = new javax.swing.JButton();
        btAddAdvertising = new javax.swing.JButton();
        labelIconActia = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescrition = new javax.swing.JTextArea();
        labelDescrition = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        labelMusic = new javax.swing.JLabel();
        textFieldMusic = new javax.swing.JTextField();
        btSearchMusic = new javax.swing.JButton();
        btAddMusic = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Abrir = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        fileChooser.setDialogTitle("Esta é minha caixa de diálogo aberta");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("plicação de demonstração"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        textFieldNomeRota.setText("digite um nome pra rota");
        //String nomedaVariavel = (textFieldNomeRota.getText());
        //System.out.println(nomedaVariavel);
        textFieldNomeRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeRotaActionPerformed(evt);
            }
        });
        //    public void imprimeTexto() {  
//         System.out.println(textFieldNomeRota.getText());  
//     }

        labelNomeRota.setText("Nome da Rota");

        labelTempoRota.setText("Duração da Rota");

        textFieldTempoRota.setText("digite o tempo de duração");
        textFieldTempoRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTempoRotaActionPerformed(evt);
            }
        });

        labelInstitutional.setText("Vídeo Institucional");

        textFieldInstitutional.setText("selecione o vídeo institucional");

        textFieldSecurity.setText("selecione o video de segurança");

        labelSecurity.setText("Vídeo Segurança");

        btSearchSecurity.setText("...");
        btSearchSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchSecurityActionPerformed(evt);
            }
        });

        btSearchInstitutional.setText("...");
        btSearchInstitutional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchInstitutionalActionPerformed(evt);
            }
        });

        labelFilmes.setText("Filmes");

        textFieldMovies.setText("selecione os filmes ");
        textFieldMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMoviesActionPerformed(evt);
            }
        });

        btSearchMovies.setText("...");
        btSearchMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchMoviesActionPerformed(evt);
            }
        });

        labelAdvertising.setText("Video Propaganda");

        textFieldadvertising.setText("selecine o video de propaganda");
        textFieldadvertising.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldadvertisingActionPerformed(evt);
            }
        });

        btSearchAvertising.setText("...");
        btSearchAvertising.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchAvertisingActionPerformed(evt);
            }
        });

        labelIconIrizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jfilechooserdemo/resources/company_logo.png"))); // NOI18N

        btGenerateRoute.setText("Gerar Rota");
        btGenerateRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerateRouteActionPerformed(evt);
            }
        });

        btEditRoute.setText("Editar Rota");

        btAddInstitutional.setText("Adicionar");

        btAddSecurityMovie.setText("Adicionar");

        btAddMovie.setText("Adicionar");

        btAddAdvertising.setText("Adicionar");

        labelIconActia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jfilechooserdemo/resources/powered_by_actia_3.png"))); // NOI18N

        jButton1.setText("Gravar");

        textAreaDescrition.setColumns(20);
        textAreaDescrition.setRows(5);
        jScrollPane1.setViewportView(textAreaDescrition);

        labelDescrition.setText("Descrição da Rota");

        btExit.setText("Sair");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        labelMusic.setText("Musicas");

        textFieldMusic.setText("selecione as musicas");

        btSearchMusic.setText("...");

        btAddMusic.setText("Adicionar");

        jMenu1.setText("File");

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jMenu1.add(Abrir);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenu1.add(Sair);

        MenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(labelTempoRota, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textFieldadvertising, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldMovies, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldSecurity)
                                    .addComponent(textFieldInstitutional)
                                    .addComponent(textFieldTempoRota, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btSearchAvertising, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(btSearchMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btAddMovie)
                                            .addComponent(btAddAdvertising)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btSearchSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(btSearchInstitutional, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btAddInstitutional)
                                            .addComponent(btAddSecurityMovie)))))
                            .addComponent(textFieldNomeRota, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelIconActia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelDescrition)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGenerateRoute)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btEditRoute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(labelIconIrizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNomeRota, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelAdvertising)
                                        .addComponent(labelFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelSecurity, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                        .addComponent(labelMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(2, 2, 2)))
                            .addComponent(labelInstitutional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(textFieldMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSearchMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAddMusic)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelIconIrizar)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDescrition, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNomeRota)
                            .addComponent(textFieldNomeRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldTempoRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTempoRota))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldInstitutional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSearchInstitutional)
                            .addComponent(labelInstitutional)
                            .addComponent(btAddInstitutional))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSecurity)
                            .addComponent(textFieldSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSearchSecurity)
                            .addComponent(btAddSecurityMovie))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFilmes)
                            .addComponent(textFieldMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSearchMovies)
                            .addComponent(btAddMovie))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAdvertising)
                            .addComponent(textFieldadvertising, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSearchAvertising)
                            .addComponent(btAddAdvertising))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMusic)
                    .addComponent(textFieldMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearchMusic)
                    .addComponent(btAddMusic)
                    .addComponent(btEditRoute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btExit)
                            .addComponent(jButton1)
                            .addComponent(btGenerateRoute))
                        .addGap(41, 41, 41))
                    .addComponent(labelIconActia, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);                                    
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                // What to do with the file, e.g. display it in a TextArea
                textarea.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void textFieldNomeRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeRotaActionPerformed
        // TODO add your handling code here:
        String nomedaVariavel = (textFieldNomeRota.getText());
        System.out.println("textFieldNomeRota = " + nomedaVariavel);

    }//GEN-LAST:event_textFieldNomeRotaActionPerformed

    private void textFieldTempoRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTempoRotaActionPerformed
        // TODO add your handling code here:
        String nomedaVariavel = (textFieldTempoRota.getText());
        System.out.println("textFieldTempoRota = " + nomedaVariavel);

    }//GEN-LAST:event_textFieldTempoRotaActionPerformed

    private void btSearchSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchSecurityActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);                                    
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                // What to do with the file, e.g. display it in a TextArea
                textarea.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }        
    }//GEN-LAST:event_btSearchSecurityActionPerformed

    private void textFieldMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMoviesActionPerformed
        // TODO add your handling code here:
        String nomedaVariavel = (textFieldMovies.getText());
        System.out.println("textFieldMovies = " + nomedaVariavel);
        
    }//GEN-LAST:event_textFieldMoviesActionPerformed

    private void btSearchAvertisingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchAvertisingActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);                                    
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                // What to do with the file, e.g. display it in a TextArea
                textarea.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btSearchAvertisingActionPerformed

    private void textFieldadvertisingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldadvertisingActionPerformed
        // TODO add your handling code here:
        String nomedaVariavel = (textFieldadvertising.getText());
        System.out.println("textFieldMovies = " + nomedaVariavel);
    }//GEN-LAST:event_textFieldadvertisingActionPerformed

    private void btGenerateRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateRouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGenerateRouteActionPerformed

    private void btSearchInstitutionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchInstitutionalActionPerformed
        // TODO add your handling code here:        
        int returnVal = fileChooser.showOpenDialog(this);                                    
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            
            //String name=file.getName();
            /*
            try {
                // What to do with the file, e.g. display it in a TextArea
                textarea.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }*/

            String name = fileChooser.getSelectedFile().getName();
            System.out.println("Istitucional = " + name);
            textFieldInstitutional.setText(name);
        } else {
            System.out.println("File access cancelled by user.");
        }
        
    }//GEN-LAST:event_btSearchInstitutionalActionPerformed

    private void btSearchMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchMoviesActionPerformed
          int returnVal = fileChooser.showOpenDialog(this);                                    
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                // What to do with the file, e.g. display it in a TextArea
                textarea.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btSearchMoviesActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFileChooserDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFileChooserDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFileChooserDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFileChooserDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFileChooserDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JButton btAddAdvertising;
    private javax.swing.JButton btAddInstitutional;
    private javax.swing.JButton btAddMovie;
    private javax.swing.JButton btAddMusic;
    private javax.swing.JButton btAddSecurityMovie;
    private javax.swing.JButton btEditRoute;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btGenerateRoute;
    private javax.swing.JButton btSearchAvertising;
    private javax.swing.JButton btSearchInstitutional;
    private javax.swing.JButton btSearchMovies;
    private javax.swing.JButton btSearchMusic;
    private javax.swing.JButton btSearchSecurity;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAdvertising;
    private javax.swing.JLabel labelDescrition;
    private javax.swing.JLabel labelFilmes;
    private javax.swing.JLabel labelIconActia;
    private javax.swing.JLabel labelIconIrizar;
    private javax.swing.JLabel labelInstitutional;
    private javax.swing.JLabel labelMusic;
    private javax.swing.JLabel labelNomeRota;
    private javax.swing.JLabel labelSecurity;
    private javax.swing.JLabel labelTempoRota;
    private javax.swing.JTextArea textAreaDescrition;
    private javax.swing.JTextField textFieldInstitutional;
    private javax.swing.JTextField textFieldMovies;
    private javax.swing.JTextField textFieldMusic;
    private javax.swing.JTextField textFieldNomeRota;
    private javax.swing.JTextField textFieldSecurity;
    private javax.swing.JTextField textFieldTempoRota;
    private javax.swing.JTextField textFieldadvertising;
    // End of variables declaration//GEN-END:variables
}
